### PR TITLE
Add awsmsk support

### PR DESCRIPTION
**Pull request by Rowanto**
Support for AWS MSK.

Features:
- Connect to AWS MSK based on its ARN
- Support for AWS MSK TLS and Authentication Option

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Rowanto Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=bsideup/liiklus&pullRequestId=153)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=bsideup/liiklus&pullRequestId=153) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Rowanto Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=bsideup/liiklus&pullRequestId=153)!

**Comment by bsideup** [comment]
hi @Rowanto,

Thanks for this contribution! 👍 

Do you think we can make it a special mode for the Kafka record storage instead, since the configuration seems to be the only difference after a quick look?

**Comment by Rowanto** [comment]
There are some specific AWS only option, such as the ARN, which will need also IAM profile. Are you sure that you want to mix in AWS in the kafka records storage? I would suggest to keep this one separate. 

As for the authentication, this is the only authentication AWS Kafka supports, and this is indeed native in Kafka, and can be ported in if you want. However, passing the authentication, keys, and everything else needed bouncy castle, which makes the jar triple in size. As normally kafka runs without TLS or authentication, this will not be the base use-case. And there also other authentication not supported by AWS MSK, e.g. you can run Kerberos, or just pass pre-created to keystore to your VM etc.

**Comment by bsideup** [comment]
I guess everyone will benefit from the Kafka's native authentication support, and the jar size is acceptable.Since Confluent recommends securing your Kafka (ping @gAmUssA), I would be in favour of adding it, even by paying the cost of the size.

---
As per AWS specifics, I'm thinking about re-implementing them as a thin plugin that will run before Kafka and pre-configure Kafka's parameters. WDYT?

**Pull request closed without merging**
