### PR TITLE
Pulsar: use publishTime if eventTime is not set

### PR DESCRIPTION
**Pull request by bsideup**
extracted from #176

### CODE REVIEW

**Comment by bsideup** [comment]
@Rowanto could you please take a look and confirm that the change looks good and matches yours?

**Comment by Rowanto** [comment]
yep, looks good.

**Comment by bsideup** [comment]
@Rowanto thanks!

**Comment by Rowanto** [comment]
sorry, just realized there is another test missing, which is checking that eventTime is preferred over publish time @bsideup

**Comment by bsideup** [comment]
@Rowanto ooops, missed that one. Would you like to submit it or I should?
I guess it can be done from GitHub UI:
https://github.com/bsideup/liiklus/blob/master/plugins/pulsar-records-storage/src/test/java/com/github/bsideup/liiklus/pulsar/PulsarRecordsStorageTest.java

**Comment by bsideup** [comment]
@Rowanto I submitted https://github.com/bsideup/liiklus/pull/178

**Pull request merged**
