### PR TITLE
Pulsar: test that eventTime is preferred over publishTime

### PR DESCRIPTION
**Pull request by bsideup**
Extracted from #176

### CODE REVIEW

**Comment by bsideup** [comment]
@Rowanto please take a look as well

**Comment by lanwen** [comment]
btw shouldn't liiklus have the same separation in the record - event and publish time?

**Comment by bsideup** [comment]
@lanwen it was never exposed, plus some systems do not support this separation

For manually defined timestamps it is better to explicitly have it in the payload

**Comment by Rowanto** [comment]
looks good.

**Pull request merged**
